10 : TBLOCK_START : \{
10 : TBLOCK_END : }
10 : TDELIM : \:
10 : TSEP : ,
10 : TARRAY_START : \[
10 : TARRAY_END : ]
20 : TTRUE : true
20 : TFALSE : false
30 : TSTRING : "(.*?(?<!\\))"
30 : TNUMBER : \d+(?>\.\d+)?
